name: release-manual-docs
on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
        description: 'Version tag:' 
jobs:
  docs-publish:
    if: github.event.inputs.tag != ''
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
              ${{ runner.os }}-node-
      - name: Generate Docs
        run: |
          npm ci
          npm run document-check
          npm run documentation
        env:
          SOURCE_TAG: ${{ github.event.inputs.tag }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.phpdoc/build
